estimator_node:
  ros__parameters:
    frame_id: map
    use_imu: true
    # Input topics from gym_bridge
    input_odom_topic: /car_state/odom_GT
    input_imu_topic: /car_state/vesc/sensors/imu/raw
    # Output topic
    output_odom_topic: /perfect_odom
    publish_rate: 50.0
    position_noise: 0.05
    orientation_noise: 0.01
    # Vehicle model adaptation parameters
    mu_init: 1.0
    Cf_init: 15000.0
    Cr_init: 15000.0
    mu_alpha: 0.001
    Cf_alpha: 0.001
    gate_param_update_on_straight: true
    kappa_gate_threshold: 0.01
